// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

/**
 * URL used by Prisma CLI only (`db push`, `migrate`, `studio`).
 * Prefer `DIRECT_URL` (Supabase non-pooler / port 5432) so schema changes avoid
 * transaction-pooler prepared-statement issues. Otherwise `DATABASE_URL` is used;
 * Supabase pooler URLs get `pgbouncer=true` if missing.
 */
function prismaCliDatasourceUrl(): string {
  const direct = process.env['DIRECT_URL']?.trim()
  if (direct) return direct

  const database = process.env['DATABASE_URL']?.trim() ?? ''
  if (!database) return ''

  if (/[?&]pgbouncer=true(?:&|$)/i.test(database)) return database

  const looksLikeSupabasePooler =
    /pooler\.supabase\.com/i.test(database) ||
    (/:6543(\/|\?|#|$)/.test(database) && /supabase\.com/i.test(database))

  if (looksLikeSupabasePooler) {
    return `${database}${database.includes('?') ? '&' : '?'}pgbouncer=true`
  }

  return database
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: prismaCliDatasourceUrl(),
  },
})
